2021/02/01 02:57:43 [error] 21#21: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:00:17 [error] 20#20: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:04:27 [error] 20#20: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:04:27 [error] 20#20: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:05:13 [error] 20#20: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:05:13 [error] 20#20: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:10:31 [error] 20#20: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:10:31 [error] 20#20: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:11:44 [error] 21#21: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:11:44 [error] 21#21: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:13:44 [error] 20#20: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:13:44 [error] 20#20: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:15:07 [error] 20#20: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:15:07 [error] 20#20: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:18:51 [error] 20#20: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:18:51 [error] 20#20: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:19:04 [error] 20#20: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:19:04 [error] 20#20: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:19:21 [error] 21#21: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:19:21 [error] 21#21: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:28:09 [error] 21#21: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:28:09 [error] 21#21: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:28:13 [error] 21#21: *7 no live upstreams while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://vpn/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:28:46 [error] 21#21: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:28:46 [error] 21#21: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:29:26 [error] 21#21: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /service-admin HTTP/2.0", upstream: "http://127.0.0.1:3003/service-admin", host: "api2.dev.insight2profit.local"
2021/02/01 03:29:26 [error] 21#21: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /service-admin HTTP/2.0", upstream: "http://127.0.0.1:3003/service-admin", host: "api2.dev.insight2profit.local"
2021/02/01 03:29:27 [error] 21#21: *11 no live upstreams while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /favicon.ico HTTP/2.0", upstream: "http://vpn/favicon.ico", host: "api2.dev.insight2profit.local", referrer: "https://api2.dev.insight2profit.local/service-admin"
2021/02/01 03:29:36 [error] 21#21: *14 no live upstreams while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://vpn/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:30:07 [error] 21#21: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:30:07 [error] 21#21: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /lookup/clients/insight/tables/clients/versions/2/members HTTP/1.1", upstream: "http://127.0.0.1:3003/lookup/clients/insight/tables/clients/versions/2/members", host: "api2.dev.insight2profit.local", referrer: "http://localhost:3002/service-admin/clients"
2021/02/01 03:32:39 [error] 21#21: *18 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "HEAD / HTTP/1.1", upstream: "http://127.0.0.1:3003/", host: "proxy.local"
2021/02/01 03:32:39 [error] 21#21: *18 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "HEAD / HTTP/1.1", upstream: "http://127.0.0.1:3003/", host: "proxy.local"
2021/02/01 03:32:43 [error] 21#21: *18 no live upstreams while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET / HTTP/1.1", upstream: "http://vpn/", host: "proxy.local"
2021/02/01 03:32:43 [error] 21#21: *18 no live upstreams while connecting to upstream, client: 172.20.0.1, server: api2.dev.insight2profit.local, request: "GET /favicon.ico HTTP/1.1", upstream: "http://vpn/favicon.ico", host: "proxy.local", referrer: "http://proxy.local/"
2021/02/01 03:33:45 [error] 21#21: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: proxy.local, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3003/", host: "proxy.local"
2021/02/01 03:33:45 [error] 21#21: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: proxy.local, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3003/", host: "proxy.local"
2021/02/01 03:33:45 [error] 21#21: *1 no live upstreams while connecting to upstream, client: 172.20.0.1, server: proxy.local, request: "GET /favicon.ico HTTP/1.1", upstream: "http://vpn/favicon.ico", host: "proxy.local", referrer: "http://proxy.local/"
2021/02/01 03:34:13 [error] 21#21: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: proxy.local, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3003/", host: "proxy.local"
2021/02/01 03:34:13 [error] 21#21: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: proxy.local, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3003/", host: "proxy.local"
2021/02/01 03:34:13 [error] 21#21: *1 no live upstreams while connecting to upstream, client: 172.20.0.1, server: proxy.local, request: "GET /favicon.ico HTTP/1.1", upstream: "http://vpn/favicon.ico", host: "proxy.local", referrer: "http://proxy.local/"
2021/02/01 03:35:48 [error] 20#20: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: proxy.local, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3003/", host: "proxy.local"
2021/02/01 03:35:48 [error] 20#20: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: proxy.local, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3003/", host: "proxy.local"
2021/02/01 03:35:49 [error] 20#20: *2 no live upstreams while connecting to upstream, client: 172.20.0.1, server: proxy.local, request: "GET /favicon.ico HTTP/1.1", upstream: "http://vpn/favicon.ico", host: "proxy.local", referrer: "http://proxy.local/"
